services:
  backend:
    build:
      context: ./backend
    container_name: academix-backend
    environment:
      - NODE_ENV=production
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data
      - ./backend/src/uploads:/app/src/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: academix-frontend
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
    ports:
      - "3000:80"
    restart: unless-stopped

